name = "MyLib"
uuid = "20034d48-b6c3-4276-ba09-08c1d8d420ab"
authors = ["Vasilis Tsilids"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
